name: Scheduled Generate v2

on:
  schedule:
    - cron: '0 0 1,21 * *' # 每月1号和21号 UTC 00:00（可改）
  workflow_dispatch: # 也支持手动执行

jobs:
  call-eset:
    uses: ./.github/workflows/eset-v2.yml
    with:
      account: '0'
      key: '1'
      mail: fakemail
      key_type: --vpn-codes
      os: Linux
      branch: main

  send-email:
    needs: call-eset
    runs-on: ubuntu-latest
    steps:
      - name: Send result email
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com # 可换为你自用邮箱服务
          server_port: 465
          secure: true
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: GitHub Action Key Generation Report
          to: yu_huo_y@163.com
          from: "GitHub Action <${{ secrets.EMAIL_USERNAME }}>"
          content_type: text/plain
          body: |
            GitHub Action 执行完毕，请查看 Summary 页面获取完整 Key 内容：
            https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}

